### ISSUE TITLE
Load Error with Gax 0.8.9

### ISSUE THREAD

**Issue by StuartHadfield** [googleapis/gax-ruby#91]
Just flagging a possible regression:

I'm aware of https://github.com/googleapis/gax-ruby/issues/54 and that this issue is to do with file permissions + was supposed to be fixed with 0.8.4, however I've run into the following error when deploying  a rails app with gax 0.8.9 via K8s and I can't help but think it's the same issue again:

```
13:04:36 rake aborted!
13:04:36 LoadError: cannot load such file -- /srv/bundle/gems/google-gax-0.8.9/lib/google/gax/errors.rb
13:04:36 /srv/bundle/gems/bootscale-0.7.0/lib/bootscale/core_ext.rb:4:in `require'
13:04:36 /srv/bundle/gems/bootscale-0.7.0/lib/bootscale/core_ext.rb:4:in `require'
13:04:36 /srv/bundle/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `block in require'
13:04:36 /srv/bundle/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:240:in `load_dependency'
13:04:36 /srv/bundle/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `require'
13:04:36 /srv/bundle/gems/google-gax-0.8.9/lib/google/gax/api_callable.rb:32:in `<top (required)>'
13:04:36 /srv/bundle/gems/bootscale-0.7.0/lib/bootscale/core_ext.rb:4:in `require'
13:04:36 /srv/bundle/gems/bootscale-0.7.0/lib/bootscale/core_ext.rb:4:in `require'
13:04:36 /srv/bundle/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `block in require'
13:04:36 /srv/bundle/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:240:in `load_dependency'
13:04:36 /srv/bundle/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `require'
13:04:36 /srv/bundle/gems/google-gax-0.8.9/lib/google/gax.rb:30:in `<top (required)>'
13:04:36 /srv/bundle/gems/bootscale-0.7.0/lib/bootscale/core_ext.rb:4:in `require'
13:04:36 /srv/bundle/gems/bootscale-0.7.0/lib/bootscale/core_ext.rb:4:in `require'
13:04:36 /srv/bundle/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `block in require'
13:04:36 /srv/bundle/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:240:in `load_dependency'
13:04:36 /srv/bundle/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `require'
13:04:36 /srv/bundle/gems/google-cloud-vision-0.23.0/lib/google/cloud/vision/v1/image_annotator_client.rb:28:in `<top (required)>'
13:04:36 /srv/bundle/gems/bootscale-0.7.0/lib/bootscale/core_ext.rb:4:in `require'
13:04:36 /srv/bundle/gems/bootscale-0.7.0/lib/bootscale/core_ext.rb:4:in `require'
13:04:36 /srv/bundle/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `block in require'
13:04:36 /srv/bundle/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:240:in `load_dependency'
13:04:36 /srv/bundle/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `require'
13:04:36 /srv/bundle/gems/google-cloud-vision-0.23.0/lib/google/cloud/vision/v1.rb:15:in `<top (required)>'
13:04:36 /srv/bundle/gems/bootscale-0.7.0/lib/bootscale/core_ext.rb:4:in `require'
13:04:36 /srv/bundle/gems/bootscale-0.7.0/lib/bootscale/core_ext.rb:4:in `require'
13:04:36 /srv/bundle/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `block in require'
13:04:36 /srv/bundle/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:240:in `load_dependency'
13:04:36 /srv/bundle/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `require'
13:04:36 /srv/bundle/gems/google-cloud-vision-0.23.0/lib/google/cloud/vision/service.rb:18:in `<top (required)>'
13:04:36 /srv/bundle/gems/bootscale-0.7.0/lib/bootscale/core_ext.rb:4:in `require'
13:04:36 /srv/bundle/gems/bootscale-0.7.0/lib/bootscale/core_ext.rb:4:in `require'
13:04:36 /srv/bundle/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `block in require'
13:04:36 /srv/bundle/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:240:in `load_dependency'
13:04:36 /srv/bundle/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `require'
13:04:36 /srv/bundle/gems/google-cloud-vision-0.23.0/lib/google/cloud/vision/project.rb:18:in `<top (required)>'
13:04:36 /srv/bundle/gems/bootscale-0.7.0/lib/bootscale/core_ext.rb:4:in `require'
13:04:36 /srv/bundle/gems/bootscale-0.7.0/lib/bootscale/core_ext.rb:4:in `require'
13:04:36 /srv/bundle/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `block in require'
13:04:36 /srv/bundle/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:240:in `load_dependency'
13:04:36 /srv/bundle/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `require'
13:04:36 /srv/bundle/gems/google-cloud-vision-0.23.0/lib/google/cloud/vision.rb:17:in `<top (required)>'
13:04:36 /srv/bundle/gems/bootscale-0.7.0/lib/bootscale/core_ext.rb:4:in `require'
13:04:36 /srv/bundle/gems/bootscale-0.7.0/lib/bootscale/core_ext.rb:4:in `require'
13:04:36 /srv/bundle/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `block in require'
13:04:36 /srv/bundle/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:240:in `load_dependency'
13:04:36 /srv/bundle/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `require'
13:04:36 /srv/bundle/bundler/gems/my_app-f051dd78048b/lib/my_app.rb:20:in `<top (required)>'
13:04:36 /srv/bundle/gems/bootscale-0.7.0/lib/bootscale/core_ext.rb:4:in `require'
13:04:36 /srv/bundle/gems/bootscale-0.7.0/lib/bootscale/core_ext.rb:4:in `require'
13:04:36 /srv/code/config/application.rb:7:in `<top (required)>'
13:04:36 /srv/code/Rakefile:5:in `require'
13:04:36 /srv/code/Rakefile:5:in `<top (required)>'
13:04:36 /usr/local/rbenv/versions/2.3.3/bin/bundle:23:in `load'
13:04:36 /usr/local/rbenv/versions/2.3.3/bin/bundle:23:in `<main>'
13:04:36 (See full trace by running task with --trace)
```

Works perfectly on development environment.
Ruby version: ruby 2.3.3p222

**Comment by StuartHadfield** [comment]
0.8.10 fixes the problem, 👍 , thanks for the rapid response @geigerj .
